name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Style Conformance
        run: |
          cd backend
          flake8 src/ tests/
      
      - name: Security
        run: |
          cd backend
          bandit -r src/ -ll
      
      - name: Tests + Coverage
        run: |
          cd backend
          pytest --cov=src --cov-report=term-missing --cov-fail-under=70
      
      - name: Cyclomatic Complexity
        run: |
          cd backend
          radon cc src/ -a -s
      
      - name: Maintainability Index
        run: |
          cd backend
          radon mi src/
